# -*- coding: utf-8 -*-

# Places
PLACE_NAME_PART1 = ('Accursed', 'Ancient', 'Baneful', 'Batrachian', 'Black', 'Bloodstained',
                    'Cold', 'Dark', 'Devouring', 'Diabolical', 'Ebon', 'Eldritch', 'Forbidden', 'Forgotten',
                    'Haunted', 'Hidden', 'Lonely', 'Lost', 'Malevolent', 'Misplaced', 'Nameless', 'Ophidian',
                    'Scarlet', 'Secret', 'Shrouded', 'Squamous', 'Strange', 'Tenebrous', 'Uncanny',
                    'Unspeakable', 'Unvanquished', 'Unwholesome', 'Vanishing', 'Weird')
PLACE_NAME_PART2 = ('room', 'hall', 'place', 'pit', 'shamble', 'crossing', 'location', 'center',
                    'cavity', 'cell', 'hollow', 'alcove', 'antechamber', 'wherabouts')
PLACE_NAME_PART3 = ('the Axolotl', 'Blood', 'Bones', 'Chaos', 'Curses', 'the Dead', 'Death',
                    'Demons', 'Despair', 'Deviltry', 'Doom', 'Evil', 'Fire', 'Frost', 'the 8 Geases', 'Gloom',
                    'Hells', 'Horrors', 'Ichor', 'Ice', 'Id Insinuation', 'the Idol', 'Iron',
                    'Madness', 'Mirrors', 'Mists', 'Monsters', 'Mystery', 'Necromancy',
                    'Oblivion', 'Peril', 'Phantasms', 'Random Harlots', 'Secrets', 'Shadows',
                    'Sigils', 'Skulls', 'Slaughter', 'Sorcery', 'Syzygy', 'Terror', 'Torment',
                    'Treasure', 'the Undercity', 'the Underworld', 'the Unknown', 'Whispers')

#Names
MALE_NAME_LIST = ["Abaet", "Abarden", "Aboloft", "Acamen", "Achard", "Ackmard", "Adeen",
                  "Aerden", "Afflon", "Aghon", "Agnar", "Ahalfar", "Ahburn", "Ahdun", "Aidan", "Airen",
                  "Airis", "Albright", "Aldaren", "Alderman", "Aldren", "Alkirk", "Allso", "Amerdan",
                  "Amitel", "Anfar", "Anumi", "Anumil", "Asden", "Asdern", "Asen", "Aslan", "Atar", "Atgur",
                  "Atlin", "Auchfor", "Auden", "Ault", "Ayrie", "Aysen", "Bacohl", "Badeek", "Baduk", "Balati",
                  "Baradeer", "Barkydle", "Basden", "Bayde", "Beck", "Bedic", "Beeron", "Bein", "Beson",
                  "Besur", "Besurlde", "Bewul", "Biedgar", "Bildon", "Biston", "Bithon", "Boal", "Boaldelr",
                  "Bolrock", "Brakdern", "Breanon", "Bredere", "Bredin", "Bredock", "Breen", "Brighton",
                  "Bristan", "Buchmeid", "Bue", "Busma", "Buthomar", "Bydern", "Caelholdt", "Cainon",
                  "Calden", "Camchak", "Camilde", "Cardon", "Casden", "Cayold", "Celbahr", "Celorn",
                  "Celthric", "Cemark", "Cerdern", "Cespar", "Cether", "Cevelt", "Chamon", "Chesmarn",
                  "Chidak", "Cibrock", "Cipyar", "Ciroc", "Codern", "Colthan", "Connell", "Cordale", "Cos",
                  "Cosdeer", "Cuparun", "Cusmirk", "Cydare", "Cylmar", "Cythnar", "Cyton", "Daburn", "Daermod",
                  "Dak", "Dakamon", "Dakkone", "Dalburn", "Dalmarn", "Dapvhir", "Darkboon", "Darkkon", "Darko",
                  "Darkspur", "Darmor", "Darpick", "Dasbeck", "Dask", "Deathmar", "Defearon", "Derik", "Derrin",
                  "Desil", "Dessfar", "Dinfar", "Dismer", "Doceon", "Dochrohan", "Dokoran", "Dorn", "Dosoman",
                  "Drakoe", "Drakone", "Drandon", "Drit", "Dritz", "Drophar", "Dryden", "Dryn", "Duba", "Dukran",
                  "Duran", "Durmark", "Dusaro", "Dyfar", "Dyten", "Eard", "Eckard", "Efamar", "Efar",
                  "Egmardern", "Eiridan", "Ekgamut", "Eli", "Elik", "Elson", "Elthin", "Enbane", "Endor",
                  "Enidin", "Enoon", "Enro", "Erikarn", "Erim", "Eritai", "Escariet", "Espardo", "Etar",
                  "Etburn", "Etdar", "Ethen", "Etmere", "Etran", "Eythil", "Faoturk", "Faowind", "Fearlock",
                  "Fenrirr", "Fetmar", "Feturn", "Ficadon", "Fickfylo", "Fildon", "Firedorn", "Firiro",
                  "Floran", "Folmard", "Fraderk", "Fronar", "Fydar", "Fyn", "Gafolern",
                  "Gai", "Galain", "Galiron", "Gametris", "Gauthus", "Gemardt", "Gemedern", "Gemedes",
                  "Gerirr", "Geth", "Gib", "Gibolock", "Gibolt", "Gith", "Gom", "Gosford", "Gothar",
                  "Gothikar", "Gresforn", "Grimie", "Gryn", "Gundir", "Gustov", "Guthale", "Gybol",
                  "Gybrush", "Gyin", "Halmar", "Harrenhal", "Hasten", "Hectar", "Hecton", "Heramon",
                  "Hermenze", "Hermuck", "Hezak", "Hildale", "Hildar", "Hileict", "Hydale", "Hyten",
                  "Iarmod", "Idon", "Ieli", "Ieserk", "Ikar", "Ilgenar", "Illilorn", "Illium", "Ingel",
                  "Ipedorn", "Irefist", "Ironmark", "Isen", "Isil", "Ithric", "Jackson", "Jalil",
                  "Jamik", "Janus", "Jayco", "Jaython", "Jesco", "Jespar", "Jethil", "Jex", "Jib",
                  "Jibar", "Jin", "Juktar", "Julthor", "Jun", "Justal", "Kafar", "Kaldar", "Kellan",
                  "Keran", "Kesad", "Kesmon", "Kethren", "Kib", "Kibidon", "Kiden", "Kilbas", "Kilburn",
                  "Kildarien", "Kimdar", "Kinorn", "Kip", "Kirder", "Kodof", "Kolmorn", "Kyrad",
                  "Lackus", "Lacspor", "Laderic", "Lafornon", "Lahorn", "Laracal", "Ledale", "Leit",
                  "Lephar", "Lephidiles", "Lerin", "Lesphares", "Letor", "Lidorn", "Lin", "Liphanes",
                  "Loban", "Lox", "Ludokrin", "Luphildern", "Lupin", "Lurd", "Macon", "Madarlon", "Mafar",
                  "Marderdeen", "Mardin", "Markard", "Markdoon", "Marklin", "Mashasen", "Mathar", "Medarin",
                  "Medin", "Mellamo", "Meowol", "Merdon", "Meridan", "Merkesh", "Mesah", "Mesard",
                  "Mesophan", "Mesoton", "Mezo", "Michael", "Mick", "Mickal", "Migorn", "Milo",
                  "Miphates", "Mitalrythin", "Mitar", "Modric", "Modum", "Mudon", "Mufar", "Mujarin", "Mylo",
                  "Mythik", "Mythil", "Nadeer", "Nalfar", "Namorn", "Naphates", "Neowyld", "Nidale", "Nikpal",
                  "Nikrolin", "Niktohal", "Niro", "Noford", "Nothar", "Nuthor", "Nuwolf", "Nydale",
                  "Nythil", "Otho", "Ocarin", "Occelot", "Occhi", "Odaren", "Odeir", "Ohethlic",
                  "Okar", "Omaniron", "Omarn", "Orin", "Ospar", "Othelen", "Oxbaren", "Padan", "Palid",
                  "Papur", "Peitar", "Pelphides", "Pender", "Pendus", "Perder", "Perol", "Phairdon",
                  "Phemedes", "Phexides", "Phoenix", "Picon", "Pictal", "Picumar", "Pildoor", "Pixdale",
                  "Ponith", "Poran", "Poscidion", "Prothalon", "Puthor", "Pyder", "Qeisan", "Qidan",
                  "Quiad", "Quid", "Quiss", "Qupar", "Qysan", "Radag'mal", "Randar", "Raysdan", "Rayth",
                  "Reaper", "Resboron", "Reth", "Rethik", "Rhithik", "Rhithin", "Rhysling", "Riandur",
                  "Rikar", "Rismak", "Riss", "Ritic", "Rogeir", "Rogist", "Rogoth", "Rophan",
                  "Rulrindale", "Rydan", "Ryfar", "Ryfar", "Ryodan", "Rysdan", "Rythen", "Rythern",
                  "Sabal", "Sadareen", "Safilix", "Samon", "Samot", "Sasic", "Scoth", "Scythe", "Secor",
                  "Sed", "Sedar", "Senick", "Senthyril", "Serin", "Sermak", "Seryth", "Sesmidat", "Seth",
                  "Setlo", "Shade", "Shadowbane", "Shane", "Shard", "Shardo", "Shillen", "Silco", "Sildo",
                  "Silforrin", "Silpal", "Sithik", "Soderman", "Sothale", "Staph", "Stenwulf",
                  "Suktor", "Suth", "Sutlin", "Syr", "Syth", "Sythril", "Talberon", "Telpur", "Temil",
                  "Temilfist", "Tempist", "Teslanar", "Tespar", "Tessino", "Tethran", "Thiltran", "Tholan",
                  "Tibers", "Tibolt", "Ticharol", "Tilner", "Tithan", "Tobale", "Tol’Solie", "Tolle",
                  "Tolsar", "Toma", "Tothale", "Tousba", "Towerlock", "Tuk", "Tuscanar", "Tusdar", "Tyden",
                  "Uerthe", "Ugmar", "Uhrd", "Undin", "Updar", "Uther", "Vaccon", "Vacone", "Valkeri",
                  "Valynard", "Vectomon", "Veldahar", "Vespar", "Vethelot", "Victor", "Vider", "Vigoth",
                  "Vilan", "Vildar", "Vinald", "Vinkolt", "Virde", "Voltain", "Volux", "Voudim",
                  "Vythethi", " ", "Wak’dern", "Walkar", "Wanar", "Wekmar", "Werymn", "Weshin",
                  "Willican", "Wilte", "Wiltmar", "Wishane", "Witfar", "Wrathran", "Wraythe", "Wuthmon",
                  "Wyder", "Wyeth", "Wyvorn", "Xander", "Xavier", "Xenil", "Xex", "Xithyl", "Xuio",
                  "Yreth", "Yabaro", "Yepal", "Yesirn", "Yssik", "Yssith", "Zak", "Zakarn",
                  "Zecane", "Zeke", "Zerin", "Zessfar", "Zidar", "Zigmal", "Zile",
                  "Zilocke", "Zio", "Zoru", "Zotar", "Zutar", "Zyten"]
FEMALE_NAME_LIST = ["Acele", "Acholate", "Ada", "Adiannon", "Adorra", "Ahanna", "Akara",
                    "Akassa", "Akia", "Amaerilde", "Amara", "Amarisa", "Amarizi", "Ana", "Andonna", "Ani",
                    "Annalyn", "Archane", "Ariannona", "Arina", "Arryn", "Asada", "Awnia", "Ayne", "Basete",
                    "Bathelie", "Bethe", "Brana", "Brianan", "Bridonna", "Brynhilde", "Calene", "Calina", "Celestine",
                    "Celoa", "Cephenrene", "Chani", "Chivahle", "Chrystyne", "Corda", "Cyelena", "Dalavesta", "Desini",
                    "Dylena", "Ebatryne", "Ecematare", "Efari", "Enaldie", "Enoka", "Enoona", "Errinaya", "Fayne",
                    "Frederika", "Frida", "Gene", "Gessane", "Gronalyn", "Gvene", "Gwethana", "Halete", "Helenia",
                    "Hildandi", "Hyza", "Idona", "Ikini", "Ilene", "Illia", "Iona", "Jessika", "Jezzine", "Justalyne",
                    "Kassina", "Kilayox", "Kilia", "Kilyne", "Kressara", "Laela", "Laenaya", "Lelani", "Lenala",
                    "Linovahle", "Linyah", "Lloyanda", "Lolinda", "Lyna", "Lynessa", "Mehande", "Melisande",
                    "Midiga", "Mirayam", "Mylene", "Nachaloa", "Naria", "Narisa", "Nelenna", "Niraya", "Nymira",
                    "Ochala", "Olivia", "Onathe", "Ondola", "Orwyne", "Parthinia", "Pascheine", "Pela", "Periel",
                    "Pharysene", "Philadona", "Prisane", "Prysala", "Pythe", "Q’ara", "Q’pala", "Quasee",
                    "Rhyanon", "Rivatha", "Ryiah", "Sanala", "Sathe", "Senira", "Sennetta", "Sepherene",
                    "Serane", "Sevestra", "Sidara", "Sidathe", "Sina", "Sunete", "Synestra", "Sythini",
                    "Szene", "Tabika", "Tabithi", "Tajule", "Tamare", "Teresse", "Tolida", "Tonica",
                    "Treka", "Tressa", "Trinsa", "Tryane", "Tybressa", "Tycane", "Tysinni", "Undaria",
                    "Uneste", "Urda", "Usara", "Useli", "Ussesa", "Venessa", "Veseere", "Voladea",
                    "Vysarane", "Vythica", "Wanera", "Welisarne", "Wellisa", "Wesolyne", "Wyeta",
                    "Yilvoxe", "Ysane", "Yve", "Yviene", "Yvonnette", "Yysara", "Zana", "Zathe",
                    "Zecele", "Zenobia", "Zephale", "Zephere", "Zerma", "Zestia", "Zilka", "Zoura", "Zrye", "Zyneste",
                    "Zynoa"]
COUNTRY_NAME_LIST = ["Abari", "Absurdsvanj", "Abysus", "Adjikistan", "Afromacoland", "Agrabah", "Agraria",
                     "Ajina", "Ajir", "Azhir", "Akhbaristan", "Al-Alemand", "Al Amarja", "Alagaesia", "Alaine",
                     "Albenistan",
                     "Allebahst", "Aldestan", "Al Hari", "Almein", "Almia", "Alpenstein", "Altruria", "Alvania",
                     "Amalah",
                     "Amerope", "Ambrosia", "Amerzone", "Amestris", "Anatruria", "Anchuria", "Andalasia", "Anemia",
                     "Angria",
                     "Annexia", "Anvilania", "Aquabania", "Aquilea", "Aragon", "Araluen", "Arcacia", "Archenland",
                     "Ardaji",
                     "Ardistan", "Ark", "Arrida", "Arstotzka", "Arulco", "Aslan", "Athbekistan", "Atlantica",
                     "Atlantis",
                     "Attilan", "Aurelia", "Auspasia", "Austrania", "Averna", "Axphain", "Ayazad", "Azania", "Azaran",
                     "Aztlan", "Azmenistan", "BabaKiueria", "Babahl", "Babalstan", "Bakaslavia", "Balamkadar",
                     "Baldova",
                     "Baki", "Balinderry", "Balnibarbi", "Baltish", "Baltonia", "Bandar", "Banania", "Bandrika",
                     "Vandreka",
                     "Bangalla", "Bangstoff", "Bantonga", "Bapetikosweti", "Baracq", "Baraza", "Barataria",
                     "Barringtonia",
                     "Basanda", "Basenji", "Bayview", "Belka", "Belsornia", "Beninia", "Bensalem", "Bereznik",
                     "Bergania",
                     "Bergenait", "Bestiolandia", "Bethjabrin", "Betonia", "Bialya", "Birani", "Blefuscu", "Blueland",
                     "Bocamoa", "Boloxnia", "Bonande", "Bongiornia", "Bongo Congo", "Bookland", "Bora Gora", "Borduria",
                     "Borginia", "Borostyria", "Borova", "Borovia", "Borovnia", "Boruguay", "Bothalia", "Brainania",
                     "Braslavia", "Bratavia", "Bratislavia", "Brazuela", "Bregna", "Bretzelburg", "Bretonnia",
                     "Brobdingnag", "Brogavia", "Brungaria", "Brutopia", "Buckyvania", "Bukistan", "Bulmeria",
                     "Bundonia", "Buranda", "Burdabi", "Burgossa", "Burmini", "Burunda", "Burunga", "Cagliostro",
                     "Calbia", "Calia", "Calormen", "Candover", "Cantania", "Carbombya", "Carpania", "Carpathia",
                     "Cascara",
                     "Caspak", "Caspiar", "Castlebury", "Caucastan", "Cayuna", "Celama", "Celtica", "Cenktrich",
                     "Champina",
                     "Chekia", "Chernarus", "Chimerica", "Chirimoyandia", "Chiroubistan", "Cimmeria", "Citysville",
                     "Chommo",
                     "Cleirville", "Cobra Island", "Cohdopia", "Concordia",
                     "Cornada", "Cornea", "Coronia", "Cortuguay", "Costaguana", "Coventry", "Coxotopia", "Crusoeland",
                     "Curaguay", "Dalmasca", "Dalmatia", "Danu", "Dasah", "Dave", "Dawsbergen", "Defastena", "Derbaran",
                     "Derkaderkastan", "Dinotopia", "Dolaronia", "Drachenschweig", "Drackenberg", "Dregovia",
                     "Dreisenberg",
                     "Dresdania", "Droon", "Dschinnistan", "Dubinia", "Duloc", "Ducklovia", "Eagleland", "Ecotopia",
                     "Ecuarico",
                     "Eisneria", "Elbonia", "Elensia", "Eleutheria", "Elkabar", "Emmeria", "Kundu", "Equestria",
                     "Eregion",
                     "Eretz", "Erewhon", "Erusea", "Estovakia", "Estrovia", "Esturia", "Etchechuria", "Ethniklashistan",
                     "Etxelur", "Euphrania", "Eurba", "Evallonia", "Evarchia", "Everon", "Fato", "Fawzia", "Fenua",
                     "Ua",
                     "Feudalia", "Findas", "Fiore", "Florin", "Foggyland", "Foo", "Franistan", "Fredonia", "Freedonia",
                     "Freiland", "Frobnia", "Gaad", "Gaaldine", "Gaillardia", "Galbadia", "Gallica", "Gamba", "Gamorra",
                     "Ganubia", "Gath", "Gatolandia", "Genosha", "Genovia", "Ghalea", "Gilboa", "Gilead", "Gindra",
                     "Giwak", "Glendovia", "Glenraven", "Glovania", "Glubbdubdrib", "Gnarnia", "Golithia", "Gondal",
                     "Gondor", "Gondour", "Gorslava", "Granbretan", "Graustark", "Grenyarnia", "Grimzinistan",
                     "Grzkijstan",
                     "Guadec", "Guadosalam", "Guamania", "Guanduria", "Guaranga", "Guilder", "Gulevandia", "Guravia",
                     "Halla", "Harmonia", "Hav", "Heartland", "Heiligwaldenstein", "Herland", "Hermajistan",
                     "Herzoslovakia",
                     "Hetland", "Hibernia", "Hidalgo", "Hili-liland", "Hillsdown", "Hoenn", "Hohenwald", "Holodrum",
                     "Hopi Hari", "Houyhnhnms", "Hudatvia", "Hyrule", "Hyrkania", "Idris", "Illyria", "Imara",
                     "Inagua", "Ingunaguay", "Iraqistan", "Iriadeska", "Ishkebar", "Ishmaelia", "Ishtar", "Istan",
                     "Isthmus", "Ivalice", "Ixania", "Jatsonia", "Javasu", "Jhamjarh", "Joanna", "Johto", "Jolliginki",
                     "Juanatopia", "Kabulstan", "Kafaristan", "Kahndaq", "Kalampore", "Kalao", "Kalny", "Kalubya",
                     "Kalya", "Kamaria", "Kamanga", "Kambezi", "Kamburu", "Kamistan", "Kampong", "Kangan", "Kanto",
                     "Karak", "Karathia", "Karistan", "Karjastan", "Karlova", "Karovia", "Kasja", "Kasnia", "Katanga",
                     "Katara", "Katzenstok", "Kaziland", "Kenyopia", "Kharun", "Khembalung", "Khemed", "Khios",
                     "Kilika", "Kimbala", "Kinakuta", "Kinjanja", "Kinkow", "Kipi Kipi", "Klopstokia", "Kukuanaland",
                     "Kurio", "Kuristan", "Kurland", "Kush", "Labrynna", "Lacroa", "Laevatia", "Lampidorra",
                     "Lani Lani",
                     "Lanconia", "Latkovia", "Latveria", "Laurania", "Lavernia", "Leasath", "Leutonia", "Libria",
                     "Lichtenburg", "Lichtenstamp", "Lilliput", "Ligeria", "Lillitania", "Lindon", "Litzenburg",
                     "Lividia", "Logosia", "Lombuanda", "Loompaland", "Lorien", "Lothlorien", "Lovitzna", "Lualia",
                     "Lucrania", "Lugash", "Luggnagg", "Lukano", "Lutha", "Luzon", "Lyrian", "Lyrobia", "Macaria",
                     "Madalu", "Madripoor", "Maestrazgo", "Maguadora", "Magyaristan", "Mahri Nui", "Mai Chow",
                     "Malafrena", "Malagawi", "Malaguay", "Malaurak", "Malbonia", "Malden", "Maldonia", "Malevelosia",
                     "Malgudi", "Malicuria", "Maltovia", "Mamaland", "Managua", "Mandalia", "Mandavia", "Mandawi",
                     "Mandoras", "Manjipur", "Mantegua", "Maraguay", "Margoth", "Marivellas", "Markovia", "Marnsburg",
                     "Masavania", "Matobo", "Mata Nui", "Maurania", "Melnibone", "Mendorra", "Meropis", "Mervo",
                     "Metrofulus", "Mgunda", "Midgar", "Mifan", "Milantis", "Mindu", "Miranda", "Mirania", "Miristan",
                     "Modova", "Mokoko", "Moloni Republic", "Mombaka", "Monica", "Morevana", "Moribundia", "Morolandia",
                     "Moronica", "Muldovia", "Munma", "Muscovy", "Mypos", "Naboombu", "Nafrece", "Nagonia", "Nambabwe",
                     "Nambutu", "Narnia", "Nato'wa", "Natumbe", "Nayak", "Nea So Copros", "Neotopia", "Neustern",
                     "Neutralia", "Neverland", "Nevoruss", "Ngombwana", "Nibia", "Nihilon", "Nihon-Ja", "Nivia",
                     "Nollop", "Nordennavic", "Norgborg", "North Elbonia", "North Sarrawak", "Novistrana",
                     "Nukehavistan",
                     "Nuku'la Atoll", "Oblivia", "Oceania", "Ohtar", "Okenland", "Olifa", "Onabushka", "Opar",
                     "Opet", "Opperland", "Opium", "Orangeland", "Orb", "Oriense", "Oriosa", "Orre", "Orsinia",
                     "Osaze", "Osterlich", "Ostnia", "Ostnitz", "Ovitznia", "Osea", "Ostrichishishouia", "Outer Heaven",
                     "Paflagonia", "Paiiz", "Pala", "Palmont", "Palombia", "Panau", "Panem", "Panquita", "Palmolive",
                     "Parador", "Paragonia", "Parazuela", "Parmistan", "Paslan", "Pathos", "Patusan", "Peaceland",
                     "Pelegostos", "Pepeslavia", "Pepperland", "Percebelandia", "Perusalem", "Petoria", "Phaic Tan",
                     "Pharamaul", "Phatt Island", "Pfennig Halbpfennig", "Pianostan", "Picta", "Pigmania",
                     "Plunder Island", "Poictesme", "Poketopia", "Pokolistan", "Pokoponesia", "Poldavia",
                     "Polrugaria", "Pomerania", "Pontevedro", "Porchesia", "Porto Guava", "Porto Santo",
                     "Potarneyland", "Pottibakia", "Pottsylvania", "Povia", "Poyais", "Pulsovia", "Prajevitza",
                     "Prance", "Qamadan", "Quaramonte", "Qumar", "Qumran (Kumrahn)", "Qum Qum", "Qurac", "Radiata",
                     "Ragaan", "Rapture", "Ramat", "Raspur", "Rauick", "Ravi", "Razkavia", "Realia", "Redonda",
                     "Rendoosia", "Rezzapyrk", "Rhodia", "Riallaro", "Riechtenburg", "Rogatine", "Rolisica",
                     "Romanovia",
                     "Ronguay", "Rohan", "Rudyardia", "Rumackistan", "Ruritania", "Rubovia", "Rukovia", "Rumekistan",
                     "Rundoon", "Runovia", "Sachenia", "Sacramento", "Sahelise Republic", "Sahrani",
                     "Saint Marie", "Salcedo", "Salkikas", "Salamia", "Salouf", "Salvjakestan", "Samaru", "Samavia",
                     "Sapogonia", "Saradia", "Sarahtopia", "Sarasaland", "Sarkhan", "Saroczia", "Saudi-Israelia",
                     "Sauville", "Scabb Island", "Schiermeeuwenoog", "Selgina", "Seravno", "Sercia", "Serdaristan",
                     "Serena Republic", "Sevii Islands", "Shadaloo", "Shakobi", "Shakoor", "Shangri-La",
                     "Shipwreck Cove",
                     "Shundi", "Shmoldovia", "Sibirska", "Sierra Gordo", "SimNation", "Sinnoh", "Skandia", "Skandistan",
                     "Skeptos", "Skull Island", "Slabovia", "Slaka", "Slavatania", "Slavosk", "Slobovia", "Sloravia",
                     "Slorenia", "Slovetzia", "Sodor", "Sonzola", "Sotho", "Spensonia", "Spira", "Spydravania",
                     "Stenden", "Strong Badia", "Strackenz", "Svenborgia", "Sunda", "Suroq", "Svardia", "Syldavia",
                     "Sylvania", "Symkaria", "Taftan", "Taka-Tuka-Land", "Takistan", "Tanah Masa", "Tandoori",
                     "Taprobane", "Taronia", "Tawaki", "Tazbekstan", "Tazirstan", "Tecala", "Tecan", "Termina",
                     "Terresta", "Tescara", "Texarkana", "Thembria", "Thermosa", "Thulahn", "Tibecuador",
                     "Tierrapaulita",
                     "Tierra Verde", "Tijata", "Tirania", "Trans-Carpathia", "Tri City", "Tomainia", "Tontecarlo",
                     "Townsville", "Transeuratia", "Transia", "Transmania", "Transvalia", "Tratvia", "Trebekiguay",
                     "Trebond", "Treedonia", "Trent", "Tribia", "Trobokistan", "Tropico", "Trucial Abysmia", "Tsalal",
                     "Turaqistan", "Twilight Town", "Tyrania", "Tyranistan", "Tyrgyzstan", "Udrogoth", "Ulgia",
                     "Underland", "Anatidae", "Unistat", "Grisee", "Unova", "Ustio", "Uqbar", "Utopia", "Ubomo",
                     "Vadeem", "Val Verde", "Valaria", "Valeria", "Valeska", "Vandreka", "Vanutu", "Varania",
                     "Varina", "Vasaria", "Versovia", "Vespugia", "Veyska", "Vien-tan", "Vigata", "Vilena",
                     "Volsinia", "Vosnia", "Vulgaria", "Wadata", "Wadiya", "Wakanda", "Wallarya", "Waponi Wu",
                     "West Monrassa", "West Prophets", "West Xylophone", "Whereintheheckestan", "Wielvakia",
                     "Xerxes", "Yakastonia", "Yangdon", "Yatakang",
                     "Yerba", "Yudonia", "Yugaria", "Yuktobania", "Youstinkistan", "Yurp", "Yurugli",
                     "Zagorias Federation", "Zakkestan", "Zambezi", "Zambola", "Zamunda", "Zanarkand",
                     "Zandia", "Zangaro", "Zarakal", "Zarcovia", "Zekistan", "Zembala", "Zembla",
                     "Zemenia", "Zillyhoo", "Zinariya", "Zlhatovica", "Zoravia", "Inner Magadan", "Zuvendis"]